# Travis defines and exports CC and CXX *after* we have defined our
# environment variables via 'env'.  So, do not use 'env' to define
# them.  Instead, put their definitions in MATRIX_EVAL, which we eval
# after the definitions from Travis.

language: cpp

env:
  global:
    # ICC serial number.
    # See https://github.com/nemequ/icc-travis.
    secure: B3manbbi0anCAGDJTdAa9TlodzRHeiYD87FKmFzS877dPm8Cm0BDvtUhKBUpBvP8+nbHOWFGrgDmLugSZjTGU+mAxtuQpamUFHvinu0BIk3qtjlqouwvbtIqUu8iiZ3Uqu+xKeAANKRy0YVZGLlEb9F3N119tJ/Fxp1p9bXL1qph+CZ25OFbUgZ2s4F+/AyHMUxJlNXKFe3Qean65hC6edhU3zoaKzr/g/wtbhRmcyWbkOa1dJqzr2yKotcPvrnApGhDzgMKFtohg/t7xfMADDVv6sGS5XNpt25Z+MUCmLg4Z9eD7u109jvRV1eu/jgVafqsthWEhXbuMiFgFhKBKGCNZ0dACIfKZSkFZI6FdM7ovJ6aNhSlxZ2169Ybd22rN1UTHeCQWySPcVVOg5taLVpqe+E8Xhnv4hBO5NrzElWwCMLxIdPUSwVStYvtDr8ZytHWzfot50vSnFKIFpTOr9hP4+AJMVmmqJfaJo2MLBft/q2xkztrMv3lQSj3m4+ma9kPDwXIu9uCutjlnhc00jNx9qegi5VfpAjxcG1R+pX4T20az6ByHk/7LPQsANkT31RJq/jAeD9LEuMOy8miha83q4QuvbFaqPK3PY0el/O1LZaXqLsV2aQ0uqH8YX0l4r5NzHdhb+3lYgvpMBO5ytr/EWJiEyNYV518050IUDE=

matrix:
  include:
    ## ------- ##
    ## First.  ##
    ## ------- ##

    # Start with three completely different environments, to get
    # errors asap.

    - name: "GCC 7 -O3"
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CONFIGUREFLAGS='CPPFLAGS=-DNDEBUG CFLAGS=-O3 CXXFLAGS=-O3'"

    - name: "Clang 3.5"
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
          packages:
            - clang-3.5
      env:
        - MATRIX_EVAL="CC=clang-3.5 && CXX=clang++-3.5"

    - name: "Clang 3.4"
      os: linux
      # Not available on Xenial.
      dist: trusty
      addons:
        apt:
          packages:
            - clang-3.4
      env:
        # No versioned name installed, but beware that Travis installs
        # a more modern clang earlier in the default PATH.
        - MATRIX_EVAL='CC=/usr/bin/clang && CXX=/usr/bin/clang++ && GETTEXT_VERSION=0.18.3'

    - name: "Clang 3.3"
      os: linux
      # Not available on Xenial.
      dist: trusty
      addons:
        apt:
          packages:
            - clang-3.3
      env:
        # See comment for 3.4.
        - MATRIX_EVAL='CC=/usr/bin/clang && CXX=/usr/bin/clang++ && GETTEXT_VERSION=0.18.3'


before_install:
  - eval "$MATRIX_EVAL"
  - env
  - sudo apt-get update -qq
  - sudo apt-get install -qq autoconf automake autopoint doxygen flex gettext graphviz help2man m4 texinfo
  - if [[ $CC == "icc" ]]; then build-aux/install-icc.sh; fi
  - if [[ -f ~/.bashrc ]]; then source ~/.bashrc; fi
  # Install and activate dmd
  - mkdir -p ~/dlang && wget https://dlang.org/install.sh -O ~/dlang/install.sh
  - source $(source ~/dlang/install.sh dmd -a)
  - autoconf --version
  - automake --version
  - autopoint --version
  - $CC --version
  - $CXX --version
  - dmd --version
  - doxygen --version
  - flex --version
  - gettext --version
  - dot -V
  - help2man --version
  - ld --version
  - m4 --version
  - makeinfo --version

script:
  - git tag -l
  # For some reasons, sometimes the checkout does not have any tags,
  # so `git describe` fails, so bootstrap fails.
  - git describe || git tag v3.0 -m "Fake version 3.0."
  - git describe
  # Unset this variable, otherwise, Java programs' stderr is cluttered
  # with `Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m`, which makes
  # the test suite fail.
  - unset _JAVA_OPTIONS
  - if [[ $GETTEXT_VERSION ]]; then sed -i -re "s/(AM_GNU_GETTEXT_VERSION).*/\1([$GETTEXT_VERSION])/" configure.ac; fi
  - ./bootstrap
  # For some reason, gnulib-po/Makefile.in.in is about Gettext 0.19, so it will break here.  Override it.
  - if [[ $GETTEXT_VERSION ]]; then autopoint --force; fi
  - if [[ -f ~/.bashrc ]]; then source ~/.bashrc; fi
  - ./configure --enable-gcc-warnings CC="$CC" CXX="$CXX" $CONFIGUREFLAGS || { cat config.log && false; }
  - make -j2 $MAKE_ARGS
  - if test ${PART-1} = 1; then make check                  VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat test-suite.log && cat tests/testsuite.log && false; }; fi
  - if test ${PART-1} = 1; then make maintainer-check-posix VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat tests/testsuite.log && false; }; fi
  - if test ${PART-2} = 2; then make maintainer-check-g++   VERBOSE=1 TESTSUITEFLAGS=-j2 || { cat tests/testsuite.log && false; }; fi

after_script:
  - if [[ $CC == "icc" ]]; then uninstall_intel_software; fi
